<?xml version="1.0"?>
<!-- CORBA XML document created by XMLSerializer2 1.5 at 2024-09-27 09:06:40 UTC, from SL 2.57-r18860 built 2010-10-20 16:48:30 UTC -->
<!DOCTYPE any [
<!ELEMENT any (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)?>
<!ATTLIST any name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED version CDATA #IMPLIED>
<!ELEMENT typecode (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)?>
<!ATTLIST typecode name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT sequence ((any|typecode|sequence|array|struct|union|exception|string|objectref)+|(enum|boolean|char|octet|short|ushort|long|ulong|float|double))?>
<!ATTLIST sequence name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED length NMTOKEN #REQUIRED bound NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT array ((any|typecode|sequence|array|struct|union|exception|string|objectref)+|(enum|boolean|char|octet|short|ushort|long|ulong|float|double))?>
<!ATTLIST array name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED length NMTOKEN #REQUIRED label NMTOKEN #IMPLIED>
<!ELEMENT struct (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)*>
<!ATTLIST struct name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT union (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)*>
<!ATTLIST union name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT exception (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)*>
<!ATTLIST exception name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT string (#PCDATA)>
<!ATTLIST string name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED bound NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT objectref (#PCDATA)>
<!ATTLIST objectref name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT enum (#PCDATA)>
<!ATTLIST enum name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED values NMTOKENS #REQUIRED label NMTOKEN #IMPLIED>
<!ELEMENT boolean (#PCDATA)>
<!ATTLIST boolean name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT char (#PCDATA)>
<!ATTLIST char name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT octet (#PCDATA)>
<!ATTLIST octet name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT short (#PCDATA)>
<!ATTLIST short name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT ushort (#PCDATA)>
<!ATTLIST ushort name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT long (#PCDATA)>
<!ATTLIST long name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT ulong (#PCDATA)>
<!ATTLIST ulong name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT float (#PCDATA)>
<!ATTLIST float name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT double (#PCDATA)>
<!ATTLIST double name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
]>
<any version="1.5">
<sequence length="1" type_id="IDL:specs.de/Serializer/RegionGroupSeq:1.0" type_name="RegionGroupSeq">
<struct type_id="IDL:specs.de/Serializer/RegionGroup:1.0" type_name="RegionGroup">
<string name="name">N1s hv50</string>
<sequence name="regions" length="1" type_id="IDL:specs.de/Serializer/RegionDataSeq:1.0" type_name="RegionDataSeq">
<struct type_id="IDL:specs.de/Serializer/RegionData:1.0" type_name="RegionData">
<string name="name">N1s</string>
<struct name="region" type_id="IDL:specs.de/SurfaceAnalysis/RegionDef:1.0" type_name="RegionDef">
<string name="analysis_method">XPS</string>
<string name="analyzer_lens">MediumArea:1.5kV</string>
<string name="detector_dataset">phoibos150-MCD</string>
<string name="detector_dataset_directory">C:\Program Files\SPECS\SpecsLab2\database\datasetCalib1d</string>
<string name="analyzer_slit">5:7x20\2:open</string>
<struct name="scan_mode" type_id="IDL:specs.de/SurfaceAnalysis/ScanMode:1.0" type_name="ScanMode">
<string name="name">FixedAnalyzerTransmission</string>
<ulong name="flags" type_id="IDL:specs.de/SurfaceAnalysis/ScanModeFlags:1.0" type_name="ScanModeFlags">2</ulong>
</struct>
<ulong name="num_scans">1</ulong>
<ulong name="curves_per_scan">1</ulong>
<ulong name="values_per_curve">201</ulong>
<double name="dwell_time">1</double>
<double name="scan_delta">0.1</double>
<double name="excitation_energy">1253.6</double>
<double name="kinetic_energy">840.6</double>
<double name="kinetic_energy_base">0</double>
<double name="pass_energy">50</double>
<double name="bias_voltage">90</double>
<double name="detector_voltage">2800</double>
<double name="effective_workfunction">3.76</double>
</struct>
<ulong name="mcd_head">50</ulong>
<ulong name="mcd_tail">54</ulong>
<struct name="analyzer_info" type_id="IDL:specs.de/SurfaceAnalysis/AnalyzerInfo:1.0" type_name="AnalyzerInfo">
<string name="name">PHOIBOS HSA3500 150 R6[HWType 30:14] MCD-9</string>
<sequence name="detectors" length="9" type_id="IDL:specs.de/SurfaceAnalysis/DetectorSeq:1.0" type_name="DetectorSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-32</double>
<double name="shift">-0.108385</double>
<double name="gain">1</double>
<sequence name="parameters" length="2" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Threshold [mV]</string>
<any name="value">
<double>16.26953125</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Deadtime [ns]</string>
<any name="value">
<double>-0</double>
</any>
</struct>
</sequence>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-24</double>
<double name="shift">-0.081073</double>
<double name="gain">1</double>
<sequence name="parameters" length="2" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Threshold [mV]</string>
<any name="value">
<double>3.828125</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Deadtime [ns]</string>
<any name="value">
<double>-0</double>
</any>
</struct>
</sequence>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-16</double>
<double name="shift">-0.054284</double>
<double name="gain">1</double>
<sequence name="parameters" length="2" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Threshold [mV]</string>
<any name="value">
<double>3.828125</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Deadtime [ns]</string>
<any name="value">
<double>-0</double>
</any>
</struct>
</sequence>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-8</double>
<double name="shift">-0.028249</double>
<double name="gain">1</double>
<sequence name="parameters" length="2" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Threshold [mV]</string>
<any name="value">
<double>3.828125</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Deadtime [ns]</string>
<any name="value">
<double>-0</double>
</any>
</struct>
</sequence>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">0</double>
<double name="shift">-0.001986</double>
<double name="gain">1</double>
<sequence name="parameters" length="2" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Threshold [mV]</string>
<any name="value">
<double>3.828125</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Deadtime [ns]</string>
<any name="value">
<double>-0</double>
</any>
</struct>
</sequence>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">8</double>
<double name="shift">0.023707</double>
<double name="gain">1</double>
<sequence name="parameters" length="2" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Threshold [mV]</string>
<any name="value">
<double>3.828125</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Deadtime [ns]</string>
<any name="value">
<double>-0</double>
</any>
</struct>
</sequence>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">16</double>
<double name="shift">0.0494</double>
<double name="gain">1</double>
<sequence name="parameters" length="2" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Threshold [mV]</string>
<any name="value">
<double>3.828125</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Deadtime [ns]</string>
<any name="value">
<double>-0</double>
</any>
</struct>
</sequence>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">24</double>
<double name="shift">0.075636</double>
<double name="gain">1</double>
<sequence name="parameters" length="2" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Threshold [mV]</string>
<any name="value">
<double>3.828125</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Deadtime [ns]</string>
<any name="value">
<double>-0</double>
</any>
</struct>
</sequence>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">32</double>
<double name="shift">0.09971</double>
<double name="gain">1</double>
<sequence name="parameters" length="2" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Threshold [mV]</string>
<any name="value">
<double>3.828125</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Deadtime [ns]</string>
<any name="value">
<double>-0</double>
</any>
</struct>
</sequence>
</struct>
</sequence>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct name="source_info" type_id="IDL:specs.de/SurfaceAnalysis/SourceInfo:1.0" type_name="SourceInfo">
<string name="name">XRayDummy</string>
<sequence name="excitations" length="1" type_id="IDL:specs.de/SurfaceAnalysis/ExcitationSeq:1.0" type_name="ExcitationSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Excitation:1.0" type_name="Excitation">
<double name="energy">1253.6</double>
<double name="lorentz_width">0.7</double>
<double name="gauss_width">0</double>
<double name="intensity">1</double>
</struct>
</sequence>
<sequence name="parameters" length="5" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Anode</string>
<any name="value">
<enum values="Mg Al Ag AlMono AgMono Y_M_zeta Zr_M_zeta Nb_M_zeta Mo_M_zeta Ti_L_alpha Cr_L_alpha Ni_L_alpha Cu_L_alpha Mg_K_alpha Al_K_alpha Si_K_alpha Y_L_alpha Zr_L_alpha Au_M_alpha Mo_L_alpha Ag_L_alpha Ti_K_alpha Cr_K_alpha Cu_K_alpha AlMicro1 AlMicro2 AlMicro3 AlMicro4 UserDefined" type_id="IDL:specs.de/XRayAnode/Anode:1.0" type_name="Anode">Mg</enum>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Power [W]</string>
<any name="value">
<double>150</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Voltage [kV]</string>
<any name="value">
<double>10</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Angle [deg]</string>
<any name="value">
<double>310</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">End of acquisition</string>
<any name="value">
<enum values="Off Standby Operate" type_id="IDL:specs.de/SurfaceAnalysis/SourceState:1.0" type_name="SourceState">Off</enum>
</any>
</struct>
</sequence>
<boolean name="intensity_scaling">0</boolean>
</struct>
<struct name="remote_info" type_id="IDL:specs.de/SurfaceAnalysis/RemoteInfo:1.0" type_name="RemoteInfo">
<string name="name"/>
<enum name="frequency" values="Never PerRegion PerScan PerValue AfterRegion AfterScan AfterValue" type_id="IDL:specs.de/SurfaceAnalysis/RemoteFrequency:1.0" type_name="RemoteFrequency">Never</enum>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
<sequence name="channel_names" length="0" type_id="IDL:specs.de/SurfaceAnalysis/StringSeq:1.0" type_name="StringSeq"/>
<sequence name="channel_units" length="0" type_id="IDL:specs.de/SurfaceAnalysis/StringSeq:1.0" type_name="StringSeq"/>
</struct>
<sequence name="cycles" length="1" type_id="IDL:specs.de/Serializer/CycleSeq:1.0" type_name="CycleSeq">
<struct type_id="IDL:specs.de/Serializer/Cycle:1.0" type_name="Cycle">
<ulong name="time">1709779102</ulong>
<sequence name="scans" length="1" type_id="IDL:specs.de/Serializer/ScanSeq:1.0" type_name="ScanSeq">
<struct type_id="IDL:specs.de/Serializer/ScanData:1.0" type_name="ScanData">
<sequence name="counts" length="2745" type_id="IDL:specs.de/SurfaceAnalysis/CountsSeq:1.0" type_name="CountsSeq">
<ulong type_id="IDL:specs.de/SurfaceAnalysis/Counts:1.0" type_name="Counts">
0
1172
635
2392
1784
2521
2946
2133
1467
1
1117
592
2427
1745
2564
3015
2123
1446
1
1049
628
2387
1741
2597
3009
2075
1463
1
1135
603
2342
1786
2558
2965
2184
1480
1
1079
564
2340
1748
2509
2937
2129
1431
0
1122
606
2348
1769
2540
3027
2106
1385
0
1167
653
2375
1806
2572
2981
2107
1454
2
1092
561
2363
1783
2528
2991
2160
1395
0
1091
625
2337
1777
2472
2980
2162
1405
0
1093
619
2315
1768
2624
2970
2127
1399
0
1108
624
2313
1741
2611
2970
2098
1434
0
1108
616
2359
1747
2522
2915
2194
1419
0
1075
634
2324
1708
2665
3052
2106
1448
0
1103
646
2377
1778
2514
3048
2119
1441
0
1108
575
2382
1741
2531
2961
2136
1450
0
1090
599
2280
1748
2586
2982
2111
1448
0
1123
626
2264
1782
2568
2953
2133
1449
0
1077
605
2280
1780
2583
3008
2102
1432
1
1167
612
2389
1720
2598
3022
2224
1429
0
1056
638
2302
1691
2577
2942
2178
1490
1
1158
647
2363
1775
2462
2954
2120
1520
0
1076
610
2441
1789
2528
2948
2148
1419
0
1115
619
2366
1656
2542
3017
2069
1417
0
1125
606
2418
1685
2541
2985
2122
1469
0
1088
579
2358
1794
2463
2945
2141
1422
0
1059
591
2356
1839
2508
2957
2158
1442
0
1128
602
2336
1747
2524
2944
2141
1437
0
1102
579
2360
1735
2553
2959
2114
1508
0
1048
599
2356
1765
2452
3104
2184
1475
0
1082
629
2383
1747
2563
2941
2083
1428
0
1057
611
2344
1825
2558
2930
2096
1465
0
1108
652
2347
1767
2549
2988
2129
1452
1
1074
624
2416
1754
2577
3015
2144
1474
0
1120
603
2296
1762
2563
2979
2121
1437
0
1082
636
2395
1672
2696
3045
2113
1450
1
1075
611
2395
1769
2543
2972
2090
1436
0
1145
652
2401
1727
2573
2954
2181
1435
0
1107
601
2308
1734
2566
2983
2084
1526
0
1080
627
2318
1738
2543
3055
2124
1488
1
1145
653
2264
1841
2541
2888
2180
1489
0
1112
597
2396
1800
2547
3005
2086
1487
1
1089
634
2344
1725
2488
2931
2107
1482
0
1114
601
2401
1798
2501
2920
2143
1434
1
1107
600
2360
1781
2569
3046
2188
1487
0
1078
578
2423
1766
2563
2975
2121
1468
0
1051
665
2266
1785
2532
3015
2115
1408
0
1093
638
2408
1755
2520
3070
2211
1452
1
1074
615
2304
1748
2599
2982
2128
1431
1
1099
635
2325
1695
2606
3065
2084
1472
1
1062
607
2393
1806
2579
3071
2228
1495
0
1034
607
2337
1746
2518
2953
2144
1492
0
1135
624
2301
1725
2572
2940
2172
1396
0
1076
642
2412
1742
2571
2949
2150
1481
1
1104
635
2417
1805
2647
3028
2168
1449
0
1113
645
2428
1702
2581
3071
2124
1408
0
1111
578
2407
1821
2537
3070
2093
1421
0
1143
615
2315
1800
2604
2997
2138
1428
1
1088
586
2265
1709
2658
2898
2106
1475
0
1163
561
2369
1751
2674
2975
2185
1545
0
1060
543
2271
1766
2565
2990
2046
1421
0
1074
592
2414
1675
2527
2952
2169
1461
2
1107
620
2246
1749
2578
3010
2101
1460
0
1121
593
2367
1714
2636
2904
2114
1454
0
1055
625
2317
1778
2485
2925
2160
1399
1
1081
645
2284
1680
2572
3139
2162
1421
2
1124
602
2351
1775
2489
3005
2161
1514
0
1139
570
2402
1787
2481
2976
2122
1492
1
1094
657
2356
1696
2634
3033
2182
1530
0
1069
621
2387
1745
2507
2855
2128
1536
1
1103
606
2343
1740
2540
2957
2142
1454
1
1067
592
2264
1752
2539
2936
2207
1476
1
1119
593
2349
1768
2541
3055
2144
1482
0
1080
605
2311
1743
2531
3038
2157
1463
0
1105
630
2377
1746
2565
3082
2137
1580
0
1099
649
2321
1805
2568
2995
2162
1477
1
1071
612
2390
1761
2551
3131
2251
1511
1
1118
584
2268
1760
2532
3048
2235
1482
0
1094
673
2377
1819
2621
3047
2151
1462
0
1106
640
2457
1784
2623
3015
2147
1406
0
1101
582
2285
1783
2598
2955
2145
1454
0
1133
571
2288
1739
2561
3093
2214
1494
1
1121
606
2374
1728
2594
2958
2156
1530
1
1090
597
2357
1801
2630
2888
2165
1442
0
1065
606
2318
1727
2428
2901
2132
1483
0
1107
620
2326
1700
2582
3023
2134
1494
0
1088
608
2402
1737
2583
2977
2220
1512
0
1031
587
2333
1749
2551
3001
2230
1511
1
1078
620
2326
1754
2529
3063
2182
1423
1
1029
601
2457
1779
2537
2900
2274
1482
0
1097
627
2253
1741
2523
2902
2140
1468
0
1116
615
2337
1682
2527
3014
2151
1469
0
1102
604
2341
1761
2566
3057
2213
1466
0
1088
595
2337
1699
2631
3008
2247
1514
0
1090
655
2232
1671
2584
3093
2225
1416
0
1111
613
2362
1752
2691
3062
2102
1486
0
1095
621
2304
1757
2531
3046
2240
1546
1
1115
600
2407
1807
2533
3105
2229
1461
1
1059
624
2402
1712
2578
3096
2263
1510
0
1122
577
2390
1620
2577
3091
2145
1476
0
1127
629
2390
1744
2685
3093
2218
1472
0
1049
554
2319
1746
2617
3195
2197
1497
0
1082
603
2325
1743
2537
3029
2111
1492
0
1125
630
2344
1834
2607
3081
2269
1495
0
1078
562
2470
1836
2591
3092
2258
1493
0
1105
594
2290
1699
2660
2946
2248
1482
0
1110
635
2292
1721
2535
3036
2209
1537
1
1036
607
2331
1784
2529
2967
2278
1522
0
1112
601
2333
1812
2577
3125
2179
1498
1
1121
607
2282
1760
2513
3005
2126
1513
1
1108
623
2294
1719
2641
3092
2186
1536
0
1120
595
2313
1740
2506
3089
2181
1568
0
1070
589
2309
1799
2569
3049
2274
1529
0
1123
647
2390
1806
2490
3088
2183
1567
1
1088
656
2396
1777
2603
3051
2210
1647
1
1084
634
2317
1776
2529
3043
2210
1563
0
1100
644
2398
1826
2654
3017
2200
1574
0
1084
622
2349
1737
2614
3092
2237
1588
0
1097
587
2324
1886
2649
3015
2174
1603
0
1100
605
2389
1775
2696
3117
2286
1632
1
1044
616
2298
1761
2535
3123
2278
1608
0
1202
605
2316
1733
2613
3133
2260
1632
0
1124
612
2397
1799
2528
3102
2290
1641
1
1084
617
2363
1726
2634
3046
2275
1600
1
1109
645
2411
1740
2679
3155
2220
1702
0
1111
611
2348
1786
2636
3127
2318
1616
0
1172
624
2410
1734
2590
3047
2400
1644
0
1120
621
2331
1837
2647
3122
2252
1690
0
1111
589
2288
1738
2622
3001
2392
1675
2
1131
577
2428
1732
2618
3093
2318
1692
0
1145
584
2383
1810
2611
3007
2268
1698
0
1088
622
2342
1779
2592
3139
2348
1764
0
1116
625
2349
1821
2542
3071
2389
1767
1
1115
640
2408
1749
2600
2998
2429
1718
0
1138
636
2435
1702
2678
3072
2424
1753
0
1066
582
2332
1824
2583
3065
2470
1749
0
1051
626
2347
1773
2648
3228
2524
1705
0
1051
616
2384
1797
2663
3191
2371
1716
0
1110
601
2384
1829
2580
3285
2460
1728
1
1091
638
2326
1767
2628
3134
2474
1788
0
1107
605
2427
1813
2665
3209
2569
1718
0
1097
575
2400
1814
2640
3227
2543
1779
0
1115
631
2460
1822
2648
3247
2495
1697
0
1118
582
2418
1804
2617
3306
2519
1757
0
1096
603
2415
1916
2601
3305
2520
1745
0
1085
604
2361
1844
2750
3322
2563
1783
1
1078
569
2389
1881
2735
3338
2610
1730
1
1126
585
2384
1830
2666
3353
2518
1704
2
1124
640
2361
1770
2628
3361
2573
1740
0
1074
636
2376
1798
2733
3460
2603
1662
1
1155
581
2422
1796
2704
3463
2625
1773
0
1132
584
2427
1836
2694
3535
2650
1722
0
1110
568
2419
1825
2729
3545
2606
1685
0
1072
610
2420
1862
2748
3500
2604
1661
0
1139
631
2413
1857
2780
3583
2524
1736
0
1122
642
2372
1897
2768
3497
2603
1626
1
1109
554
2441
1712
2756
3548
2492
1642
2
1122
631
2459
1902
2869
3576
2600
1560
0
1178
628
2440
1781
2847
3691
2431
1567
0
1126
640
2449
1802
2770
3562
2467
1578
1
1134
648
2512
1909
2888
3480
2504
1536
0
1136
673
2411
1823
2817
3681
2536
1501
0
1094
660
2434
1845
2918
3544
2540
1506
0
1113
619
2401
1808
2915
3557
2459
1465
0
1138
632
2435
1917
2869
3703
2426
1468
0
1106
632
2372
1803
2951
3626
2417
1404
1
1091
627
2456
1850
2930
3564
2390
1490
0
1103
633
2448
1824
2994
3562
2389
1445
0
1151
642
2358
1847
3137
3673
2377
1406
0
1122
643
2432
1973
3094
3691
2211
1546
1
1162
644
2518
1973
3040
3630
2233
1529
1
1124
632
2461
1948
3078
3584
2366
1441
0
1139
617
2462
1979
3034
3529
2319
1454
0
1151
632
2467
2041
3043
3466
2258
1478
0
1109
616
2470
1920
3026
3560
2222
1446
0
1133
656
2531
1985
3067
3507
2180
1444
0
1098
612
2538
2067
3054
3448
2220
1445
0
1159
623
2548
1976
3139
3343
2152
1432
0
1103
628
2497
2113
3024
3366
2160
1431
1
1140
625
2551
2046
3180
3407
2165
1374
0
1176
698
2585
2118
2963
3343
2127
1392
0
1103
670
2622
1993
2950
3262
2173
1446
2
1119
642
2579
2104
3045
3302
2189
1435
0
1118
638
2599
2152
2992
3205
2169
1444
0
1139
719
2590
2153
3093
3210
2219
1376
0
1073
675
2601
2146
3029
3247
2131
1397
0
1163
679
2664
2126
3051
3151
1997
1430
0
1104
643
2706
2109
2941
3007
2088
1431
0
1147
662
2627
1995
2973
3118
2166
1448
0
1055
694
2711
2105
2967
3119
2054
1442
1
1237
641
2747
2167
3005
3083
2137
1399
1
1133
634
2791
2106
2865
3118
2122
1489
1
1166
651
2768
2101
2832
3055
2113
1423
0
1094
630
2715
2255
2824
2975
2188
1425
0
1135
651
2748
2101
2907
2949
2117
1457
0
1165
687
2753
2057
2762
3026
2142
1447
2
1128
641
2800
2042
2772
2938
2143
1416
0
1118
669
2732
2122
2732
2955
2167
1445
2
1166
718
2848
2061
2670
2971
2079
1498
0
1184
740
2810
2090
2689
2926
2096
1390
0
1157
679
2836
2023
2674
2980
2136
1406
0
1145
704
2884
2076
2511
3033
2135
1415
1
1126
698
2859
2003
2699
2910
2114
1425
0
1190
693
2833
1974
2622
2961
2096
1411
0
1178
665
2794
1998
2560
2917
2101
1451
0
1173
738
2877
1895
2524
2953
2110
1460
2
1237
727
2814
1981
2525
2944
2084
1374
0
1236
703
2714
1921
2430
2959
2170
1420
0
1229
723
2846
1850
2490
2960
2134
1439
0
1188
735
2860
1934
2556
2916
2078
1455
0
1220
741
2816
1883
2586
2958
2103
1401
0
1250
697
2706
1864
2510
2919
2088
1381
1
1142
706
2784
1824
2547
2951
2176
1490
0
1212
761
2820
1878
2415
2977
2131
1436
0
1218
727
2759
1873
2492
2919
2117
1474
0
1202
759
2674
1714
2454
2933
2084
1472
0
1331
745
2727
1802
2567
2932
2109
1480
0
1296
754
2607
1662
2491
2917
2094
1460
0
1291
766
2756
1780
2530
3036
2167
1424
0
1278
700
2642
1749
2508
2894
2094
1495
1
1244
756
2606
1782
2557
2975
2104
1494
0
1274
736
2515
1715
2528
2951
2123
1493
0
1185
748
2508
1725
2511
2882
2128
1470
0
1347
709
2554
1779
2549
3030
2168
1534
0
1369
729
2422
1683
2512
2900
2098
1449
0
1378
710
2429
1701
2453
2924
2081
1419
0
1316
778
2365
1674
2519
3026
2097
1448
0
1373
689
2394
1771
2457
2930
2154
1431
0
1321
705
2333
1816
2509
2953
2164
1526
0
1276
717
2321
1699
2394
2899
2216
1443
1
1290
641
2374
1697
2493
3000
2203
1443
0
1321
754
2338
1724
2567
3063
2141
1474
1
1343
642
2312
1700
2450
2947
2144
1470
0
1319
645
2424
1731
2474
2854
2171
1395
0
1351
683
2319
1643
2574
2964
2146
1437
1
1331
702
2375
1694
2527
3027
2115
1460
0
1305
672
2259
1691
2519
2877
2166
1434
0
1288
647
2317
1723
2524
3024
2180
1481
0
1251
631
2258
1684
2577
3060
2091
1396
0
1278
649
2365
1738
2503
2916
2165
1475
0
1324
654
2287
1721
2487
3014
2145
1458
0
1268
647
2305
1756
2465
2939
2202
1496
1
1311
617
2276
1651
2492
2958
2222
1393
2
1253
612
2236
1796
2573
2965
2153
1427
0
1246
593
2309
1781
2585
2963
2132
1512
0
1183
643
2286
1703
2629
2962
2188
1442
0
1210
608
2407
1719
2538
3053
2192
1446
1
1247
571
2439
1752
2588
3053
2123
1414
0
1190
582
2328
1708
2529
3037
2167
1449
0
1215
635
2369
1677
2558
3023
2139
1424
0
1203
618
2232
1764
2520
2999
2092
1467
1
1149
587
2290
1808
2464
2975
2152
1465
0
1155
630
2344
1746
2474
3027
2165
1489
0
1115
579
2355
1729
2573
3029
2070
1467
1
1114
578
2307
1677
2527
3047
2141
1441
1
1141
574
2275
1735
2543
2982
2132
1404
0
1163
621
2381
1699
2440
2967
2157
1416
0
1127
613
2270
1730
2652
3087
2084
1440
0
1138
556
2315
1693
2571
2982
2177
1418
1
1080
581
2294
1732
2662
2884
2166
1474
0
1081
594
2300
1727
2624
3065
2107
1389
1
1111
612
2320
1741
2662
3044
2212
1354
0
1143
600
2311
1815
2502
2966
2050
1454
1
1103
619
2265
1788
2556
2997
2188
1463
0
1118
629
2389
1805
2584
2944
2146
1358
0
1028
597
2337
1728
2606
2968
2081
1403
1
1060
576
2343
1697
2593
2987
2164
1396
1
1099
656
2304
1723
2547
3005
2186
1467
1
1083
557
2306
1833
2527
3034
2163
1394
0
1120
649
2322
1716
2533
2935
2173
1455
0
1052
594
2312
1700
2661
2909
2085
1388
0
1056
599
2298
1720
2540
2909
2099
1331
0
1068
596
2378
1771
2592
2993
2118
1426
0
1140
577
2397
1748
2544
2932
2104
1382
2
1098
595
2397
1814
2668
3068
2113
1405
0
1111
618
2360
1756
2630
2971
2214
1455
0
1031
600
2390
1719
2608
2955
2024
1494
0
1041
569
2310
1773
2610
3012
2136
1459
0
1042
594
2343
1789
2476
2950
2132
1431
0
1053
631
2293
1744
2627
2898
2052